### ISSUE TITLE
example localAssets class

### ISSUE THREAD

**Issue by cornernote** [aarondfrancis/mantis-manager#3]
Is there an example localAssets class?

**Comment by aarondfrancis** [comment]
I'd recommend using Gulp these days. This hasn't been touched in quite some
time.

**Comment by cornernote** [comment]
I basically just wanted something that merges all my css/js via a yii command, I took what you had and created this:

https://github.com/cornernote/yii-dressing/blob/master/yii-dressing/commands/YdAssetCompressCommand.php

Thanks for the starting point, it really helped!
